In [9]:
import pandas as pd

df = pd.read_csv('../data/raw/data.csv')

df.head(30)

                                                 text      category
0   Pandas is a powerful library for data manipula...        python
1   Pandas is a powerful library for data manipula...        python
2                                                 NaN        python
3                                         Short text.       general
4     Machine   learning   models   are   only   a...  data_science
5                                    Git is for code.        devops
6   Data cleaning is the most important step in an...  data_science
7   Scikit-learn provides simple and efficient too...        python
8   Scikit-learn provides simple and efficient too...        python
9                                                 NaN  data_science
10                                         Too short.       general
11  Feature engineering is the process of using do...  data_science
12  Neural networks are inspired by the biological...  data_science
13  Jupyter Notebook is an open-source web applica...        python
14  Overfitting occurs when a model learns the det...  data_science
15  Cross-validation is a statistical method used ...  data_science
16   Data\tcleaning\tis\tcrucial\tfor\tgood\tresults.  data_science
17     This is a text with weird spacing and tabs ...       general
18                                     DVC is useful.        devops
19                                   Pandas is great.        python
20  Git is essential for tracking changes in your ...        devops
21  DVC helps version control your machine learnin...        devops
22  DVC helps version control your machine learnin...        devops
23                                                NaN        devops
24                                  A very short one.       general
25  Regularization is a technique used to prevent ...  data_science
26  Hyperparameter tuning is the process of choosi...  data_science
27    Lots   of   extra   spaces   here   to   tes...        python
28  Transfer learning allows us to leverage pre-tr...  data_science
29  Natural language processing enables computers ...  data_science

In [7]:
print(df.shape)
print(df.columns)

(51, 2)
Index(['text', 'category'], dtype='str')

In [8]:
print(df.isna().sum())

text        3
category    0
dtype: int64

In [10]:
print(df["text"].duplicated().sum())

5

In [13]:
df = df.dropna(subset=["text"])
print(df.shape)

(48, 2)

In [15]:
df = df.drop_duplicates(subset=["text"])
print(df.shape)

(45, 2)

In [18]:
df["text"] = df["text"].str.strip().str.replace(r"\s+", " ", regex=True)
df.head(10)

                                                 text      category
0   Pandas is a powerful library for data manipula...        python
3                                         Short text.       general
4   Machine learning models are only as good as th...  data_science
5                                    Git is for code.        devops
6   Data cleaning is the most important step in an...  data_science
7   Scikit-learn provides simple and efficient too...        python
10                                         Too short.       general
11  Feature engineering is the process of using do...  data_science
12  Neural networks are inspired by the biological...  data_science
13  Jupyter Notebook is an open-source web applica...        python

In [21]:
df = df[df["text"].str.len() > 50]
df.head(15)

                                                 text      category
0   Pandas is a powerful library for data manipula...        python
4   Machine learning models are only as good as th...  data_science
6   Data cleaning is the most important step in an...  data_science
7   Scikit-learn provides simple and efficient too...        python
11  Feature engineering is the process of using do...  data_science
12  Neural networks are inspired by the biological...  data_science
13  Jupyter Notebook is an open-source web applica...        python
14  Overfitting occurs when a model learns the det...  data_science
15  Cross-validation is a statistical method used ...  data_science
17  This is a text with weird spacing and tabs \t\...       general
20  Git is essential for tracking changes in your ...        devops
21  DVC helps version control your machine learnin...        devops
25  Regularization is a technique used to prevent ...  data_science
26  Hyperparameter tuning is the process of choosi...  data_science
27  Lots of extra spaces here to test the regex cl...        python